language: java
jdk: openjdk8
branches:
  only:
  - master
  - "/.*-[0-9]+\\..*/"
install: true
script: ".travis/build.sh"
env:
  global:
  - secure: Mkpe2pLvssHCMTP1bL2eWRgJZbH7at65hLqe1vpYWTSFtZ7JXiDk/Uh3vB5gV35bR0gzt76qKIgGzi70AACs1lemKDQcG/7zzHsk/uh99v6lUBiN8Qn6iBBDJO+dSatX4Rg756h/tse+ziNiRqxwc/JIhA7Ty/j6ldRKKfa4Bi4=
  - secure: gPo0RS/43KG7s1peJ3FY2VI/LepF4KJff1fFbbdXPwHO5Qeg5HQBk4DmIg7aCKS7cR0TmlXHDcFPG6sO1eH6MlVcYaP7MCnQB6XwQphDMEUj3P/fJFRwNA31OGFHS4+9nqU/xVeUy03WwIzTwJhjHy533SkGJd0dOSOSiP4pucQ=
